FROM alpine:3.5

RUN apk add --update make git openssh gnupg vim shadow \
  &&  rm -f /var/cache/apk/*

RUN adduser -D -u 1000 docker_user
WORKDIR /home/docker_user

RUN echo "docker_user:docker_pass" | chpasswd

RUN mkdir .ssh/
ADD .gitconfig .
ADD id_rsa .ssh/
ADD id_rsa.pub .ssh/
ADD pubkey.asc .ssh/
ADD privkey.asc .ssh/
RUN chown docker_user:docker_user .ssh/privkey.asc

RUN pass=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1) \
        && echo 'root:${pass}' | chpasswd \
        && sed -i -e '/root/s/sh/false/g' /etc/passwd

ENV GPG_TTY /dev/pts/0

USER docker_user

RUN gpg --import /home/${user-name}/.ssh/pubkey.asc
RUN gpg --batch --import /home/${user-name}/.ssh/privkey.asc

RUN ssh-keyscan -H github.com

CMD ["/bin/sh"]
