FROM alpine:latest

RUN apk add --update make git openssh gnupg vim shadow

RUN adduser -D -u 1000 docker_user
WORKDIR /home/docker_user

RUN echo "docker_user:docker_pass" | chpasswd

RUN mkdir .ssh/
ADD .gitconfig .
ADD $HOME/id_rsa .ssh/
ADD $HOME/id_rsa.pub .ssh/
ADD pubkey.asc .ssh/
ADD privkey.asc .ssh/
RUN chown docker_user:docker_user .ssh/privkey.asc

RUN pass=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1) \
        && echo 'root:${pass}' | chpasswd \
        && usermod -s /bin/false root

USER docker_user

RUN ssh-keyscan -H github.com

ENV GPG_TTY /dev/pts/0

CMD ["/bin/sh']
