FROM alpine:latest

RUN apk --update make git openssh gnupg vim shadow

RUN add-user -D -u 1000 {{username}}
WORKDIR /home/{{username}}

RUN echo "{{username}}:{{userpassword}}" | chpasswd

RUN mkdir .ssh/
ADD .gitconfig .
ADD id_rsa .ssh/
ADD id_rsa.pub .ssh/
ADD pubkey_asc .ssh/
ADD privkey_asc .ssh/
RUN chown {{username}}:{{username}} .ssh/{{privkey_asc_file}}

RUN pass=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1) \ 
        && echo 'root:${pass}' | chpasswd \
        && usermod -s /bin/false root

USER {{username}}

RUN ssh-keyscan -H github.com

ENV GPG_TTY /dev/pts/0

CMD ["/bin/sh']
